ALTER TYPE "ActivityType"
ADD VALUE IF NOT EXISTS 'TITLE_CHANGED';

ALTER TYPE "ActivityType"
ADD VALUE IF NOT EXISTS 'DESCRIPTION_CHANGED';

ALTER TYPE "ActivityType"
ADD VALUE IF NOT EXISTS 'DUE_DATE_CHANGED';